name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm # you can omit this if you use npm
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
